[[plugins]]
repo = 'ryota2357/ddu-column-icon_filename'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = ['ddc.vim']

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = 'source ~/.local/share/dein/plugins/ddc.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']

[[plugins]]
repo = 'Shougo/ddu-column-filename'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-filter-sorter_alpha'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-filter-converter_display_word'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = ['ddu.vim']

[[plugins]]
repo = 'Shougo/ddu.vim'
hook_add = 'source ~/.local/share/dein/plugins/ddu.vim'
on_func = ['ddu#start']
depends = ['denops.vim']

[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = ['ddu.vim']

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = ['ddu.vim']
