[[plugins]]
repo = 'ojroques/vim-oscyank'
hook_add = 'source ~/.local/share/dein/plugins/vim-oscyank'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = 'source ~/.local/share/dein/plugins/ddc-vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/pum.vim'
hook_add = 'source ~/.local/share/dein/plugins/pum-vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
