[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_source = 'source ~/.local/share/dein/plugins/denops-popup-preview.vim'
on_source = ['ddc.vim']

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_source = 'source ~/.local/share/dein/plugins/lspconfig.lua'
on_source = ['ddc.vim']

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
on_source = ['feline.nvim']

[[plugins]]
repo = 'Shougo/pum.vim'
hook_source = 'source ~/.local/share/dein/plugins/pum.vim'
on_source = ['ddc.vim']

[[plugins]]
repo = 'tpope/vim-endwise'
on_event = 'InsertEnter'
