[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_add = 'source ~/.local/share/dein/plugins/nightfox.vim'

[[plugins]]
repo = 'feline-nvim/feline.nvim'
hook_add = 'source ~/.local/share/dein/plugins/feline.lua'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = 'source ~/.local/share/dein/plugins/gitsigns.lua'

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'

[[plugins]]
repo = 'ojroques/vim-oscyank'
hook_add = 'source ~/.local/share/dein/plugins/oscyank.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
