[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_add = 'source ~/.local/share/dein/plugins/nightfox-nvim'

[[plugins]]
repo = 'ojroques/vim-oscyank'
hook_add = 'source ~/.local/share/dein/plugins/vim-oscyank'

[[plugins]]
repo = 'vim-denops/denops.vim'
