[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_source = 'source ~/.local/share/dein/plugins/denops-popup-preview.vim'
on_source = ['ddc.vim']

[[plugins]]
repo = 'nvim-tree/nvim-web-devicons'
on_source = ['feline.nvim']

[[plugins]]
repo = 'Shougo/pum.vim'
hook_source = 'source ~/.local/share/dein/plugins/pum.vim'
on_source = ['ddc.vim']

[[plugins]]
repo = 'windwp/nvim-autopairs'
hook_source = 'source ~/.local/share/dein/plugins/autopairs.lua'
on_event = 'InsertEnter'
