[[plugins]]
repo = 'akinsho/toggleterm.nvim'
hook_add = 'source ~/.local/share/dein/plugins/toggleterm.lua'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
hook_add = 'source ~/.local/share/dein/plugins/nightfox.vim'

[[plugins]]
repo = 'github/copilot.vim'
hook_add = 'source ~/.local/share/dein/plugins/copilot.vim'

[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
hook_add = 'source ~/.local/share/dein/plugins/gitsigns.lua'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = 'source ~/.local/share/dein/plugins/startify.vim'

[[plugins]]
repo = 'nanozuki/tabby.nvim'
hook_add = 'source ~/.local/share/dein/plugins/tabby.lua'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = 'source ~/.local/share/dein/plugins/lspconfig.lua'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = 'source ~/.local/share/dein/plugins/lualine.lua'
depends = ['nvim-web-devicons']

[[plugins]]
repo = 'ojroques/nvim-osc52'
hook_add = 'source ~/.local/share/dein/plugins/osc52.lua'

[[plugins]]
repo = 'petertriho/nvim-scrollbar'
hook_add = 'source ~/.local/share/dein/plugins/scrollbar.lua'

[[plugins]]
repo = 'vim-denops/denops.vim'
